[2023-11-24T14:13:59.588+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:13:56.987202+00:00 [queued]>
[2023-11-24T14:13:59.599+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:13:56.987202+00:00 [queued]>
[2023-11-24T14:13:59.600+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-24T14:13:59.615+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_and_transform_laod> on 2023-11-24 14:13:56.987202+00:00
[2023-11-24T14:13:59.621+0000] {standard_task_runner.py:57} INFO - Started process 1323 to run task
[2023-11-24T14:13:59.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'extract_and_transform_laod', 'manual__2023-11-24T14:13:56.987202+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpi0xdqon0']
[2023-11-24T14:13:59.627+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask extract_and_transform_laod
[2023-11-24T14:13:59.681+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:13:56.987202+00:00 [running]> on host efa6202eecdb
[2023-11-24T14:14:00.103+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='extract_and_transform_laod' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T14:13:56.987202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T14:13:56.987202+00:00'
[2023-11-24T14:14:00.370+0000] {logging_mixin.py:151} INFO -   Code tranches         age
0             0   tous ages
1             A     0-4 ans
2             B    5-14 ans
3             C   15-44 ans
4             D   45-64 ans
5             E   65-74 ans
6             F  75 et plus
[2023-11-24T14:14:00.439+0000] {logging_mixin.py:151} INFO -         dep date_de_passage  ...  nbre_hospit_corona_h  nbre_hospit_corona_f
0        01      2022-12-26  ...                   1.0                   3.0
1        01      2022-12-26  ...                   NaN                   NaN
2        01      2022-12-26  ...                   NaN                   NaN
3        01      2022-12-26  ...                   NaN                   NaN
4        01      2022-12-26  ...                   NaN                   NaN
...     ...             ...  ...                   ...                   ...
214215  976      2023-10-24  ...                   NaN                   NaN
214216  976      2023-10-24  ...                   NaN                   NaN
214217  976      2023-10-24  ...                   NaN                   NaN
214218  976      2023-10-24  ...                   NaN                   NaN
214219  976      2023-10-24  ...                   NaN                   NaN

[212928 rows x 12 columns]
[2023-11-24T14:14:00.443+0000] {logging_mixin.py:151} INFO - fffffffffffffffffffff    code_tranches_dage         age
0                   0   tous ages
1                   1     0-4 ans
2                   2    5-14 ans
3                   3   15-44 ans
4                   4   45-64 ans
5                   5   65-74 ans
6                   6  75 et plus
[2023-11-24T14:14:00.445+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 47, in extract_and_transform_laod
    df_urgences = df_urgences.merge(df_tranches_dage, left_on='sursaud_cl_age_corona', right_on='age', how='left')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 741, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1401, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat
[2023-11-24T14:14:00.463+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=extract_and_transform_laod, execution_date=20231124T141356, start_date=20231124T141359, end_date=20231124T141400
[2023-11-24T14:14:00.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task extract_and_transform_laod (You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat; 1323)
[2023-11-24T14:14:00.525+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T14:14:00.542+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
