[2023-11-24T13:20:43.786+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.create_table manual__2023-11-24T13:20:42.749889+00:00 [queued]>
[2023-11-24T13:20:43.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.create_table manual__2023-11-24T13:20:42.749889+00:00 [queued]>
[2023-11-24T13:20:43.795+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-24T13:20:43.807+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-11-24 13:20:42.749889+00:00
[2023-11-24T13:20:43.812+0000] {standard_task_runner.py:57} INFO - Started process 417 to run task
[2023-11-24T13:20:43.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'create_table', 'manual__2023-11-24T13:20:42.749889+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpbk5fqy5f']
[2023-11-24T13:20:43.817+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask create_table
[2023-11-24T13:20:43.858+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.create_table manual__2023-11-24T13:20:42.749889+00:00 [running]> on host efa6202eecdb
[2023-11-24T13:20:44.107+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T13:20:42.749889+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T13:20:42.749889+00:00'
[2023-11-24T13:20:44.108+0000] {sql.py:274} INFO - Executing: drop  table IF EXISTS hospitalisation; 
drop  table IF EXISTS departements; 
drop  table IF EXISTS passage_urgence; 
drop  table IF EXISTS urgences_hosp;


CREATE TABLE IF NOT EXISTS hospitalisation(
        num_dep VARCHAR(10),
        date_de_passage DATE,
        PRIMARY KEY (dep,date_de_passage)
    );

CREATE TABLE IF NOT EXISTS passage_urgence(
      Code_tranches_dage INT,
      mois INT,
      num_dep VARCHAR(10),
      PRIMARY KEY (code_tranches_dage,num_dep)
    );

CREATE TABLE IF NOT EXISTS departements (
    num_dep VARCHAR(10),
    dep_name VARCHAR(50),
    region_name VARCHAR(50),
    PRIMARY KEY (num_dep)
);

CREATE TABLE IF NOT EXISTS urgences_hosp(
    dep VARCHAR(10),
    date_de_passage DATE,
    sursaud_cl_age_corona INT,
    nbre_pass_corona INT,
    nbre_pass_tot INT,
    nbre_hospit_corona INT,
    nbre_pass_corona_h INT,
    nbre_pass_corona_f INT,
    nbre_pass_tot_h INT,
    nbre_pass_tot_f INT,
    nbre_hospit_corona_h INT,
    nbre_hospit_corona_f INT,
    FOREIGN KEY (dep) REFERENCES departements(num_dep),
    FOREIGN KEY (date_de_passage) REFERENCES hospitalisation(date_de_passage),
    FOREIGN KEY (dep) REFERENCES hospitalisation(Code_tranches_dage),
    FOREIGN KEY (sursaud_cl_age_corona) REFERENCES passage_urgence(Code_tranches_dage),
    FOREIGN KEY (dep) REFERENCES passage_urgence(num_dep)
);
[2023-11-24T13:20:44.116+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T13:20:44.123+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T13:20:44.135+0000] {sql.py:418} INFO - Running statement: drop  table IF EXISTS hospitalisation; 
drop  table IF EXISTS departements; 
drop  table IF EXISTS passage_urgence; 
drop  table IF EXISTS urgences_hosp;


CREATE TABLE IF NOT EXISTS hospitalisation(
        num_dep VARCHAR(10),
        date_de_passage DATE,
        PRIMARY KEY (dep,date_de_passage)
    );

CREATE TABLE IF NOT EXISTS passage_urgence(
      Code_tranches_dage INT,
      mois INT,
      num_dep VARCHAR(10),
      PRIMARY KEY (code_tranches_dage,num_dep)
    );

CREATE TABLE IF NOT EXISTS departements (
    num_dep VARCHAR(10),
    dep_name VARCHAR(50),
    region_name VARCHAR(50),
    PRIMARY KEY (num_dep)
);

CREATE TABLE IF NOT EXISTS urgences_hosp(
    dep VARCHAR(10),
    date_de_passage DATE,
    sursaud_cl_age_corona INT,
    nbre_pass_corona INT,
    nbre_pass_tot INT,
    nbre_hospit_corona INT,
    nbre_pass_corona_h INT,
    nbre_pass_corona_f INT,
    nbre_pass_tot_h INT,
    nbre_pass_tot_f INT,
    nbre_hospit_corona_h INT,
    nbre_hospit_corona_f INT,
    FOREIGN KEY (dep) REFERENCES departements(num_dep),
    FOREIGN KEY (date_de_passage) REFERENCES hospitalisation(date_de_passage),
    FOREIGN KEY (dep) REFERENCES hospitalisation(Code_tranches_dage),
    FOREIGN KEY (sursaud_cl_age_corona) REFERENCES passage_urgence(Code_tranches_dage),
    FOREIGN KEY (dep) REFERENCES passage_urgence(num_dep)
);, parameters: None
[2023-11-24T13:20:44.140+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "dep" named in key does not exist
LINE 10:         PRIMARY KEY (dep,date_de_passage)
                 ^

[2023-11-24T13:20:44.147+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=create_table, execution_date=20231124T132042, start_date=20231124T132043, end_date=20231124T132044
[2023-11-24T13:20:44.158+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task create_table (column "dep" named in key does not exist
LINE 10:         PRIMARY KEY (dep,date_de_passage)
                 ^
; 417)
[2023-11-24T13:20:44.190+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T13:20:44.223+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
