[2023-11-22T19:11:42.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-22T19:11:41.819640+00:00 [queued]>
[2023-11-22T19:11:42.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-22T19:11:41.819640+00:00 [queued]>
[2023-11-22T19:11:42.812+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T19:11:42.825+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_and_transform> on 2023-11-22 19:11:41.819640+00:00
[2023-11-22T19:11:42.831+0000] {standard_task_runner.py:57} INFO - Started process 1418 to run task
[2023-11-22T19:11:42.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'extract_and_transform', 'manual__2023-11-22T19:11:41.819640+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpgzdn6rt5']
[2023-11-22T19:11:42.836+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask extract_and_transform
[2023-11-22T19:11:42.882+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-22T19:11:41.819640+00:00 [running]> on host 006c0c385fe8
[2023-11-22T19:11:43.124+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='extract_and_transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T19:11:41.819640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T19:11:41.819640+00:00'
[2023-11-22T19:11:43.340+0000] {logging_mixin.py:151} INFO -   Code tranches         age
0             0   tous ages
1             A     0-4 ans
2             B    5-14 ans
3             C   15-44 ans
4             D   45-64 ans
5             E   65-74 ans
6             F  75 et plus
[2023-11-22T19:11:43.394+0000] {python.py:194} INFO - Done. Returned value was: (    num_dep                 dep_name                 region_name
0        01                      Ain        Auvergne-Rhône-Alpes
1        02                    Aisne             Hauts-de-France
2        03                   Allier        Auvergne-Rhône-Alpes
3        04  Alpes-de-Haute-Provence  Provence-Alpes-Côte d'Azur
4        05             Hautes-Alpes  Provence-Alpes-Côte d'Azur
..      ...                      ...                         ...
96      971               Guadeloupe                  Guadeloupe
97      972               Martinique                  Martinique
98      973                   Guyane                      Guyane
99      974               La Réunion                  La Réunion
100     976                  Mayotte                     Mayotte

[101 rows x 3 columns],         dep date_de_passage  ...  nbre_acte_tot_h  nbre_acte_tot_f
0        01      2022-12-26  ...              NaN              NaN
1        01      2022-12-26  ...              NaN              NaN
2        01      2022-12-26  ...              NaN              NaN
3        01      2022-12-26  ...              NaN              NaN
4        01      2022-12-26  ...              NaN              NaN
...     ...             ...  ...              ...              ...
214215  976      2023-10-24  ...              NaN              NaN
214216  976      2023-10-24  ...              NaN              NaN
214217  976      2023-10-24  ...              NaN              NaN
214218  976      2023-10-24  ...              NaN              NaN
214219  976      2023-10-24  ...              NaN              NaN

[212928 rows x 18 columns],    code_tranches_dage         age
0                   0   tous ages
1                   1     0-4 ans
2                   2    5-14 ans
3                   3   15-44 ans
4                   4   45-64 ans
5                   5   65-74 ans
6                   6  75 et plus)
[2023-11-22T19:11:43.448+0000] {xcom.py:661} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-11-22T19:11:43.452+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 145, in serialize
    return encode(classname, version, serialize(data, depth + 1))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 124, in serialize
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 124, in <listcomp>
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 143, in serialize
    data, classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
  File "pyarrow/table.pxi", line 3557, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column num_dep with type object')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2023-11-22T19:11:43.464+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=extract_and_transform, execution_date=20231122T191141, start_date=20231122T191142, end_date=20231122T191143
[2023-11-22T19:11:43.478+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task extract_and_transform (Object of type tuple is not JSON serializable; 1418)
[2023-11-22T19:11:43.491+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T19:11:43.511+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
